title: Directory
author: Andreas
email: andreas@neumeier.org
description: > # this means to ignore newlines until "show_exerpts:"
  An approach to collect and classify sites that provide news and blogs.
  A public bookmark collection, that aims to be machine readable.

theme: minima

header_pages:
  - README.md
  - urls.md
