timeout: "20m0s"
steps:
  - name: 'eu.gcr.io/$PROJECT_ID/python-builder' # Cloud Build automatically substitutes $PROJECT_ID for your Project ID
    entrypoint: '/bin/bash'
    args: ['-c','virtualenv /workspace/venv' ]
    # Creates a Python virtualenv stored in /workspace/venv that will persist across container runs.
    id: createVirtualEnv
  - name: 'eu.gcr.io/$PROJECT_ID/python-builder'
    entrypoint: 'venv/bin/pip'
    args: ['install', '-V', '-r', 'requirements.txt']
    id: setupRequirements
    # Installs any dependencies listed in the project's requirements.txt.
  - name: 'eu.gcr.io/$PROJECT_ID/python-builder'
    entrypoint: 'venv/bin/sphinx-build'
    args: ['-M', 'html', '.', 'build']
    id: sphinxBuild
    # Installs any dependencies listed in the project's requirements.txt.
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./build/html", "gs://directory.pramari.de"]
